services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin01
      POSTGRES_PASSWORD: Pa55w.rd
      POSTGRES_DB: Production
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
